const ERROR_CODES = {
  // Authentication
  INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
  UNAUTHORIZED: "AUTH_UNAUTHORIZED",
  FORBIDDEN: "AUTH_FORBIDDEN",
  TOKEN_EXPIRED: "AUTH_TOKEN_EXPIRED",
  INVALID_TOKEN: "AUTH_INVALID_TOKEN",

  // User
  USER_NOT_FOUND: "USER_NOT_FOUND",
  USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",

  // Validation
  VALIDATION_ERROR: "VALIDATION_ERROR",

  // Database
  DATABASE_ERROR: "DATABASE_ERROR",

  // General
  NOT_FOUND: "RESOURCE_NOT_FOUND",
  INTERNAL_ERROR: "INTERNAL_SERVER_ERROR",
};

export default ERROR_CODES;
